# -*- coding: utf-8 -*-
"""EPC05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1azYGBgDeKHiTTHdTBYd680pApLqlr1Fp
"""

#!pip install -U scikit-fuzzy

import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl

temp = ctrl.Antecedent(np.linspace(800, 1200, 500), 'temperatura')
vol = ctrl.Antecedent(np.linspace(2, 12, 500), 'volume')
pres = ctrl.Consequent(np.linspace(4, 12, 500), 'pressão')

#Definir universos:
temp['baixa'] = fuzz.trapmf(temp.universe, [800, 800, 900, 1000])
temp['média'] = fuzz.trimf(temp.universe, [900, 1000, 1100])
temp['alta'] = fuzz.trapmf(temp.universe, [1000, 1100, 1200, 1200])

vol['pequeno'] = fuzz.trapmf(vol.universe, [2, 2, 4.5, 7])
vol['médio'] = fuzz.trimf(vol.universe, [4.5, 7, 9.5])
vol['grande'] = fuzz.trapmf(vol.universe, [7, 9.5, 12, 12])

pres['baixa'] = fuzz.trapmf(pres.universe, [4, 4, 5, 8])
pres['média'] = fuzz.trimf(pres.universe, [6, 8, 10])
pres['alta'] = fuzz.trapmf(pres.universe, [8, 11, 12, 12])

#Vizualizar funções de pertinência e padrões geométricos:
temp.view()
vol.view()
pres.view()

#Regras:
r1 = ctrl.Rule(temp['baixa'] & vol['pequeno'], pres['baixa'])
r2 = ctrl.Rule(temp['média'] & vol['pequeno'], pres['baixa'])
r3 = ctrl.Rule(temp['alta'] & vol['pequeno'], pres['média'])
r4 = ctrl.Rule(temp['baixa'] & vol['médio'], pres['baixa'])
r5 = ctrl.Rule(temp['média'] & vol['médio'], pres['média'])
r6 = ctrl.Rule(temp['alta'] & vol['médio'], pres['alta'])
r7 = ctrl.Rule(temp['baixa'] & vol['grande'], pres['média'])
r8 = ctrl.Rule(temp['média'] & vol['grande'], pres['alta'])
r9 = ctrl.Rule(temp['alta'] & vol['grande'], pres['alta'])

#Função de sistema de controle das regras:
r_ctrl = ctrl.ControlSystem([r1, r2, r3, r4, r5, r6, r7, r8, r9])

#Função de simulação
simu = ctrl.ControlSystemSimulation(r_ctrl)

#Inicio das simulações
print('a) Temperatura x = 965°C e Volume = 11m³')
simu.input['temperatura'] = 965
simu.input['volume'] = 11
simu.compute()
print(simu.output['pressão'])
pres.view(sim=simu)

print('b) Temperatura x = 920°C e Volume = 7.6m³')
simu.input['temperatura'] = 920
simu.input['volume'] = 7.6
simu.compute()
print(simu.output['pressão'])
pres.view(sim=simu)

print('c) Temperatura x = 1050°C e Volume = 6.3m³')
simu.input['temperatura'] = 1050
simu.input['volume'] = 6.3
simu.compute()
print(simu.output['pressão'])
pres.view(sim=simu)

print('d) Temperatura x = 843°C e Volume = 8.6m³')
simu.input['temperatura'] = 843
simu.input['volume'] = 8.6
simu.compute()
print(simu.output['pressão'])
pres.view(sim=simu)

print('e) Temperatura x = 1122°C e Volume = 5.2m³')
simu.input['temperatura'] = 1122
simu.input['volume'] = 5.2
simu.compute()
print(simu.output['pressão'])
pres.view(sim=simu)